use_frameworks!

platform :ios, '9.0'

target 'LZTag_Example' do
#  pod 'LZTag', :path => '../'
  #pod 'LZTag', :git => 'https://gitee.com/Sunny0123/lztag.git'
  #pod 'LZTag', :git => 'https://github.com/lizhi0123/LZTag.git'
  pod 'LZTag'
  
  pod 'SnapKit'

  target 'LZTag_Tests' do
    inherit! :search_paths

    
  end
end
